openapi: 3.0.1
info:
  title: Reward Points API
  description: Operations related to customer reward points and transactions
  version: 1.0.0
paths:
  /reward-points:
    get:
      summary: Get all customer reward points
      description: Fetches all customer reward points
      responses:
        '200':
          description: Successfully retrieved reward points
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerRewardPoints'
        '500':
          description: Internal server error
  /reward-points/{customerId}:
    get:
      summary: Get customer reward points by customer ID
      description: Fetches reward points for a given customer ID
      parameters:
        - name: customerId
          in: path
          required: true
          description: ID of the customer to fetch reward points for
          schema:
            type: integer
      responses:
        '200':
          description: Successfully retrieved reward points
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerRewardPoints'
        '400':
          description: Invalid customer ID supplied
        '404':
          description: Customer not found
        '500':
          description: Internal server error
  /transactions:
    post:
      summary: Save transaction and reward points
      description: Saves a new transaction and calculates reward points for a customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionRequestDTO'
      responses:
        '201':
          description: Transaction and reward points successfully saved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponseDTO'
        '400':
          description: Invalid input supplied
        '500':
          description: Internal server error
components:
  schemas:
    CustomerRewardPoints:
      type: object
      properties:
        id:
          type: integer
          example: 1
        customerId:
          type: integer
          example: 123
        points:
          type: integer
          example: 150
        transactionDate:
          type: string
          format: date-time
          example: 2023-01-01T10:00:00Z
    TransactionRequestDTO:
      type: object
      properties:
        customerId:
          type: integer
          example: 123
        transactionAmount:
          type: number
          format: double
          example: 250.75
    TransactionResponseDTO:
      type: object
      properties:
        transactionId:
          type: integer
          example: 456
        rewardPoints:
          type: integer
          example: 250
